services:
  # A Node.js web service
  - type: web
    name: verbyflow-signaling
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
